version: "3.8"
services:
  server:
    image: shangri-la-server
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      FRONTEND_PREFIX: /frontend # needs also to be adjusted in the frontend package.json
      BACKEND_PREFIX: /api