#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_KEYCLOAK_USER WITH PASSWORD '$POSTGRES_KEYCLOAK_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;
	CREATE DATABASE $POSTGRES_KEYCLOAK_DB WITH ENCODING 'UTF8';
	ALTER DATABASE $POSTGRES_KEYCLOAK_DB OWNER TO $POSTGRES_KEYCLOAK_USER;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_KEYCLOAK_DB TO $POSTGRES_KEYCLOAK_USER;
EOSQL